name: Auto Sync V3 Changes

on:
  push:
    branches:
      - V3

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Sync changes to V3_New
        run: |
          git checkout V3_New
          git merge origin/V3 --no-edit
          git push origin V3_New

      - name: Sync changes to V3_Old
        run: |
          git checkout V3_Old
          git merge origin/V3 --no-edit
          git push origin V3_Old